name: Deploy Frontend to gh-pages

on:
  push:
    branches: [ main ] # Or your primary branch
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push to gh-pages branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Optional: If you had a build step (e.g., for Tailwind JIT, SASS, minification)
      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'
      #     cache: 'npm'
      #     cache-dependency-path: frontend/package-lock.json # if you have one

      # - name: Install frontend dependencies (if any)
      #   working-directory: ./frontend
      #   run: npm ci # if you have a package-lock.json

      # - name: Build frontend (if any)
      #   working-directory: ./frontend
      #   run: npm run build # if you have a build script

      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend
          # publish_branch: gh-pages # This is the default, so it's optional to specify
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy frontend to gh-pages'
          # force_orphan: true # Use this if you want to ensure a clean history on gh-pages
